[package]
name = "rustinvaders"
version = "0.1.0"
authors = [ "Chris Williams <diodesign@tuta.io>" ]
publish = false
edition = "2018"

[dependencies]
glfw = "0.31.0"
kiss3d = "0.21.0"
nalgebra = "0.18.0"
rand = "0.7.0"
